name: kstatya
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pixel_perfect: ^1.1.1
  get: ^4.6.5
  flutter_launcher_icons: ^0.10.0
  device_preview: ^1.1.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/app_icon/icon_ios.png"
  adaptive_icon_foreground: "assets/app_icon/android foreground.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Bellota
      fonts:
        - asset: assets/font/Bellota-Regular.ttf
          weight: 400
        - asset: assets/font/Bellota-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/Bellota-Light.ttf
          weight: 300
        - asset: assets/font/Bellota-Bold.ttf
          weight: 700
        - asset: assets/font/Bellota-BoldItalic.ttf
          weight: 700
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans-Light.ttf
          weight: 300
